version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: trendinalia_api
    container_name: trendinalia_api
    ports:
      - 5000:5000
    entrypoint: ['/usr/src/app/entrypoint.sh']
